// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnUJtIvKnuu5yPfOEmRZG1d3Afl8KjCP4',
    appId: '1:28144494847:android:0d9abef73c8f7efc6c44ca',
    messagingSenderId: '28144494847',
    projectId: 'easyconnect-c0ce3',
    databaseURL: 'https://easyconnect-c0ce3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'easyconnect-c0ce3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDELWoCLx5ox8bkgiS69Fod7LQqklUGzcQ',
    appId: '1:28144494847:ios:9de07293ef082ea06c44ca',
    messagingSenderId: '28144494847',
    projectId: 'easyconnect-c0ce3',
    databaseURL: 'https://easyconnect-c0ce3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'easyconnect-c0ce3.firebasestorage.app',
    iosBundleId: 'com.codecarrots.korlinks',
  );

}